# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: megahal 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "megahal"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jason Hutchens"]
  s.date = "2014-09-25"
  s.description = "MegaHAL is a grammatical inference algorithm that can generate quasi natural language sentences in the context of a conversation."
  s.email = "jasonhutchens@gmail.com"
  s.executables = ["megahal", "verify_repair"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/megahal",
    "bin/verify_repair",
    "corpora/loebner.txt",
    "corpora/sherlock.txt",
    "corpora/small.txt",
    "lib/megahal.rb",
    "lib/megahal/context.rb",
    "lib/megahal/dictionary.rb",
    "lib/megahal/distribution.rb",
    "lib/megahal/memory.rb",
    "lib/megahal/models.rb",
    "lib/megahal/models/base.rb",
    "lib/megahal/models/capitalisation.rb",
    "lib/megahal/models/memory.rb",
    "lib/megahal/models/punctuation.rb",
    "lib/megahal/models/utterance.rb",
    "lib/megahal/predictors.rb",
    "lib/megahal/predictors/base.rb",
    "lib/megahal/predictors/correlate.rb",
    "lib/megahal/predictors/insert.rb",
    "lib/megahal/predictors/markov.rb",
    "lib/megahal/predictors/repair.rb",
    "lib/megahal/session.rb",
    "megahal.gemspec",
    "run",
    "spec/context_spec.rb",
    "spec/dictionary_spec.rb",
    "spec/distribution_spec.rb",
    "spec/megahal_spec.rb",
    "spec/memory_spec.rb",
    "spec/models/base_spec.rb",
    "spec/models/capitalisation_spec.rb",
    "spec/models/memory_spec.rb",
    "spec/models/punctuation_spec.rb",
    "spec/models/spec_helper.rb",
    "spec/models/utterance_spec.rb",
    "spec/predictors/base_spec.rb",
    "spec/predictors/correlate_spec.rb",
    "spec/predictors/insert_spec.rb",
    "spec/predictors/markov_spec.rb",
    "spec/predictors/repair_spec.rb",
    "spec/predictors/spec_helper.rb",
    "spec/session_spec.rb",
    "spec/spec_helper.rb",
    "verify"
  ]
  s.homepage = "http://github.com/jasonhutchens/megahal"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "MegaHAL is a learning chatterbot."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<redcarpet>, ["~> 3.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<awesome_print>, ["~> 1.2"])
      s.add_development_dependency(%q<byebug>, ["~> 3.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<redcarpet>, ["~> 3.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<awesome_print>, ["~> 1.2"])
      s.add_dependency(%q<byebug>, ["~> 3.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<redcarpet>, ["~> 3.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<awesome_print>, ["~> 1.2"])
    s.add_dependency(%q<byebug>, ["~> 3.4"])
  end
end

