# encoding: UTF-8

module MH

  module Model

    # This model learns how to insert punctuation between IDs of a novel
    # sequence of norms that has been generated by a model. It uses two
    # predictors to achieve this; an insert predictor is used to determine
    # a distribution of puncs between each norm pair, while a TODO predictor is
    # used to make sure that the sequence of puncs is likely to be correct.
    class Punctuation < Base

      def initialize
        @_insert = MH::Predictor::Insert.new
      end

      def learn(puncs, norms)
        @_insert.observe(puncs, norms)
      end

      def generate(norms)
        @_insert.generate(norms)
      end

    end

  end

end
